name: Build Website

on:
  push:
    branches:
      - master  # Adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Choose your Python version

    - name: Install Jupyter
      run: |
        python -m pip install --upgrade pip
        pip install jupyter

    # Add more steps here for your build process, such as building Jekyll site, etc.
